services:
  app:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório atual no diretório /app do contêiner.
      # Isso permite o hot-reloading com uvicorn e persiste o banco de dados SQLite no seu host.
      - .:/app
